spring.application.name=API-Gateway
server.port=8080


spring.cloud.gateway.server.webflux.routes[0].id=studentedu-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://STUDENTEDUSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/studentedu/**,/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=attendance-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ATTENDANCESERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/attendance/**

spring.cloud.gateway.server.webflux.routes[2].id=resultedu-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://RESULTEDUSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/resultedu/**

